# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_mat_cpp <- function(coord1, coord2) {
    .Call(`_Btoolkit_distance_mat_cpp`, coord1, coord2)
}

distance_pair_cpp <- function(coord1, coord2) {
    .Call(`_Btoolkit_distance_pair_cpp`, coord1, coord2)
}

gc_distance_mat_cpp <- function(coord1, coord2) {
    .Call(`_Btoolkit_gc_distance_mat_cpp`, coord1, coord2)
}

gc_distance_pair_cpp <- function(coord1, coord2) {
    .Call(`_Btoolkit_gc_distance_pair_cpp`, coord1, coord2)
}

